package cmd

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/BurntSushi/toml"
	"github.com/spf13/cobra"

	"github.com/sennadevos/kosa/internal/backend/teable"
	"github.com/sennadevos/kosa/internal/config"
)

var initCmd = &cobra.Command{
	Use:   "init",
	Short: "set up kosa tables in a Teable base and generate config",
	Long: `Creates all 8 kosa tables with their fields in a Teable base,
then writes the config file with the generated table and field IDs.

Requires --url, --token, and --base flags.`,
	// skip the normal PersistentPreRunE (config loading) since config doesn't exist yet
	PersistentPreRunE: func(cmd *cobra.Command, args []string) error { return nil },
	RunE: func(cmd *cobra.Command, args []string) error {
		url, _ := cmd.Flags().GetString("url")
		token, _ := cmd.Flags().GetString("token")
		baseID, _ := cmd.Flags().GetString("base")
		account, _ := cmd.Flags().GetString("default-account")
		output, _ := cmd.Flags().GetString("output")

		if url == "" || token == "" || baseID == "" {
			return fmt.Errorf("--url, --token, and --base are required")
		}

		client := teable.NewClient(url, token)
		ctx := cmd.Context()

		fmt.Println("creating tables...")
		result, err := teable.Setup(ctx, client, baseID)
		if err != nil {
			return fmt.Errorf("setup failed: %w", err)
		}

		fmt.Printf("created %d tables:\n", len(result.Tables))
		for name, id := range result.Tables {
			fieldCount := len(result.Fields[name])
			fmt.Printf("  %s (%s) — %d fields\n", name, id, fieldCount)
		}

		// build config
		cfg := config.Config{
			Backend: config.BackendConfig{
				Type: "teable",
				Teable: config.TeableConfig{
					URL:    url,
					Token:  token,
					Tables: result.Tables,
					Fields: result.Fields,
				},
			},
			Defaults: config.DefaultsConfig{
				Account:  account,
				Currency: "EUR",
			},
		}

		// determine output path
		if output == "" {
			home, err := os.UserHomeDir()
			if err != nil {
				return fmt.Errorf("cannot determine home directory: %w", err)
			}
			output = filepath.Join(home, ".config", "kosa", "config.toml")
		}

		// ensure directory exists
		if err := os.MkdirAll(filepath.Dir(output), 0755); err != nil {
			return fmt.Errorf("creating config directory: %w", err)
		}

		f, err := os.Create(output)
		if err != nil {
			return fmt.Errorf("creating config file: %w", err)
		}
		defer f.Close()

		// write header comment
		fmt.Fprintln(f, "# kosa config — generated by kosa init")
		fmt.Fprintln(f, "# edit defaults below as needed")
		fmt.Fprintln(f)

		if err := toml.NewEncoder(f).Encode(cfg); err != nil {
			return fmt.Errorf("writing config: %w", err)
		}

		fmt.Printf("\nconfig written to %s\n", output)
		fmt.Println("\nnext steps:")
		fmt.Println("  1. add categories in the Teable UI (Categories table)")
		if account == "" {
			fmt.Println("  2. create accounts, then set defaults.account in config")
		} else {
			fmt.Printf("  2. create your '%s' account in the Teable UI\n", account)
		}
		fmt.Println("  3. start tracking: kosa spend 4.50 \"Coffee\"")

		// print config path for easy copy
		fmt.Printf("\n%s\n", strings.Repeat("─", 50))
		fmt.Printf("teable base: %s\n", url)
		fmt.Printf("config: %s\n", output)

		return nil
	},
}

func init() {
	initCmd.Flags().String("url", "", "teable instance URL (e.g. http://localhost:3000)")
	initCmd.Flags().String("token", "", "teable personal access token")
	initCmd.Flags().String("base", "", "teable base ID to create tables in")
	initCmd.Flags().String("default-account", "", "default account name (optional)")
	initCmd.Flags().String("output", "", "config file output path (default: ~/.config/kosa/config.toml)")
	rootCmd.AddCommand(initCmd)
}
